name: run-tests
#
#on:
#  schedule:
#    # Runs "at minute 55 past every hour" (see https://crontab.guru)
#    - cron: '*/5 * * * *'
on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out my other private repo
        uses: actions/checkout@master
        with:
          repository: STEP-tw/head-dheeraj-p
          path: 'repos/head-dheeraj-p'
      - name: Check out my other private repo
        uses: actions/checkout@master
        with:
          repository: STEP-tw/head-luckyganesh
          path: 'repos/head-luckyganesh'
      - name: Check out my other private repo
        uses: actions/checkout@master
        with:
          repository: STEP-tw/head-leelanakka
          path: 'repos/head-leelanakka'
      - name: Check out my other private repo
        uses: actions/checkout@master
        with:
          repository: STEP-tw/head-sapanakale
          path: 'repos/head-sapanakale'
      - name: Check out my other private repo
        uses: actions/checkout@master
        with:
          repository: STEP-tw/head-bsrushti
          path: 'repos/head-bsrushti'
      - name: check all directories
        run: |
          echo $GITHUB_WORKSPACE
          ls repos
          ls /home/runner/work/
          
